#!/usr/bin/env ruby

require_relative 'lib/init'


def main commands_file_path
  commands = yaml_parser.parse commands_file_path
end

def yaml_parser
  ToyRobot::ParserFactory.yaml_parser
end


commands_file_path = ARGV[0]
main commands_file_path