#!/usr/bin/env ruby

require_relative 'lib/init'


def main commands_file_path
  commands = yaml_parser.parse commands_file_path
  command_runner = create_command_runner
end

def yaml_parser
  ToyRobot::ParserFactory.yaml_parser
end

def create_command_runner
  ToyRobot::CommandRunner.new game, writer
end

def game
  ToyRobot::Game.new board, robot
end

def board

end

def robot

end

def writer

end


commands_file_path = ARGV[0]
main commands_file_path