#!/usr/bin/env ruby

require_relative 'lib/init'

def main commands_file_path
  commands = yaml_parser.parse commands_file_path
  command_runner = create_command_runner

  commands.each do |command|
    command_runner.run command
  end
end

def yaml_parser
  ToyRobot::ParserFactory.yaml_parser
end

def create_command_runner
  ToyRobot::CommandRunner.new game, stdout_writer
end

def game
  ToyRobot::Game.new board, robot
end

def board
  ToyRobot::Board.new 5, 5
end

def robot
  ToyRobot::ToyFactory.build_robot
end

def stdout_writer
  ToyRobot::WriterFactory.stdout_writer
end


commands_file_path = ARGV[0]
main commands_file_path